[package]
name = "hello_world"
version = "0.1.0"
rust-version = "1.66.1"
edition = "2018"

[[bin]]
name = "hello_world"
path = "src/main.rs"

[dependencies]
hello_lib = { path = "../hello_lib" }
hello_macro = { path = "../hello_macro" }
